/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import trandpl.dao.QuestionDAO;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.QuestionPojo;

/**
 *
 * @author hmayw
 */
public class HrEditQuizzFrame extends javax.swing.JFrame {

     private List<QuestionPojo> questions;
     private String jobId;
     private int counter;
     private QuestionPojo queRef;
    public HrEditQuizzFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblHrName.setText(CurrentUser.getName());
        questions=new ArrayList<>();
        counter=0;
    }
    public HrEditQuizzFrame(String jobId)
    {
        this();
        this.jobId=jobId;
        loadQuestions();
    }
    private void loadQuestions()
    {
       try{
           this.questions=QuestionDAO.getPaperByJobId(jobId);
           this.queRef=questions.get(counter);
           setQuestion(queRef);
       } 
       catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null,"Error in DB","Error !",JOptionPane.ERROR_MESSAGE);
           ex.printStackTrace();
       }
    }
    private void setQuestion(QuestionPojo obj)
    {
        lblQueNo.setText(String.valueOf(counter+1));
        txtQuestion.setText(obj.getQuestion());
        txtOption1.setText(obj.getOption1());
        txtOption2.setText(obj.getOption2());
        txtOption3.setText(obj.getOption3());
        txtOption4.setText(obj.getOption4());
        jcCorrectOption.setSelectedIndex(obj.getCorrectOption());
    }
    private QuestionPojo getQuestion()
    {
        QuestionPojo que=new QuestionPojo();
        que.setJobId(jobId);
        que.setqNo(Integer.parseInt(lblQueNo.getText()));
        que.setQuestion(txtQuestion.getText());
        que.setOption1(txtOption1.getText());
        que.setOption2(txtOption2.getText());
        que.setOption3(txtOption3.getText());
        que.setOption4(txtOption4.getText());
        que.setCorrectOption(jcCorrectOption.getSelectedIndex());
        return que;
    }
      private boolean validateInputs()
    {
        if(txtQuestion.getText().trim().isEmpty()||txtOption1.getText().trim().isEmpty()||txtOption2.getText().trim().isEmpty()||txtOption3.getText().trim().isEmpty()||txtOption4.getText().trim().isEmpty()||jcCorrectOption.getSelectedIndex()==0)
            return false;
        else
            return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHrName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblQueNo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnDiscardPaper = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jcCorrectOption = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtOption3 = new javax.swing.JTextField();
        txtOption2 = new javax.swing.JTextField();
        txtOption4 = new javax.swing.JTextField();
        txtOption1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuestion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(1026, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 187, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 996, 208));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblHrName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel1.add(lblHrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 170, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jLabel4.setText("Que. ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        lblQueNo.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        jPanel1.add(lblQueNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 30, 30));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel5.setText("Options : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 930, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 970, 10));

        btnPrevious.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 150, 30));

        btnNext.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 670, 140, -1));

        btnDiscardPaper.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        btnDiscardPaper.setText("Discard Paper");
        btnDiscardPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscardPaperActionPerformed(evt);
            }
        });
        jPanel1.add(btnDiscardPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 150, -1));

        btnSubmit.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 140, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel6.setText("Correnct Option : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 970, 10));

        jcCorrectOption.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jcCorrectOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select an Option", "Option 1", "Option 2", "Option 3", "Option 4" }));
        jPanel1.add(jcCorrectOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 270, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Option 4 : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, 50));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Option 3 : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Option 2 : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, 30));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setText("Option 1 : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 452, -1, 40));

        txtOption3.setBackground(new java.awt.Color(173, 192, 234));
        txtOption3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtOption3.setBorder(null);
        jPanel1.add(txtOption3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 462, 250, 30));

        txtOption2.setBackground(new java.awt.Color(173, 192, 234));
        txtOption2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtOption2.setBorder(null);
        jPanel1.add(txtOption2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 522, 240, 30));

        txtOption4.setBackground(new java.awt.Color(173, 192, 234));
        txtOption4.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtOption4.setBorder(null);
        jPanel1.add(txtOption4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 522, 250, 30));

        txtOption1.setBackground(new java.awt.Color(173, 192, 234));
        txtOption1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtOption1.setBorder(null);
        jPanel1.add(txtOption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 462, 250, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 512, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, 50));

        txtQuestion.setBackground(new java.awt.Color(173, 192, 234));
        txtQuestion.setColumns(20);
        txtQuestion.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtQuestion.setRows(5);
        jScrollPane2.setViewportView(txtQuestion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 860, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
     if(validateInputs()==false)
     {
         JOptionPane.showMessageDialog(null,"Please fill all the fields","Warning ",JOptionPane.WARNING_MESSAGE);
         return ;
     }
       queRef=getQuestion();
       questions.set(counter, queRef); 
        if(counter==0)
           counter=this.questions.size()-1;
       else 
           counter--;
       
       queRef=this.questions.get(counter);
       setQuestion(queRef); 
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
         if(validateInputs()==false)
          {
           JOptionPane.showMessageDialog(null,"Please fill all the fields","Warning ",JOptionPane.WARNING_MESSAGE);
           return ;
          }
          queRef=getQuestion();
         questions.set(counter, queRef); 
        questions.set(counter, queRef);
        if(counter==this.questions.size()-1)
             counter=0;
         else
             counter++;
         
         queRef=this.questions.get(counter);
         setQuestion(queRef);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDiscardPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscardPaperActionPerformed
        int result=JOptionPane.showConfirmDialog(null,"Are you sure, Do you want to Discard paper ","Confrimation",JOptionPane.YES_NO_OPTION);
        if(result==JOptionPane.YES_OPTION)
        {
            questions.clear();
            new HrChooseJobForSettingQuizz().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnDiscardPaperActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
       if(validateInputs()==false)
       {
           JOptionPane.showMessageDialog(null,"Please fill all the fields","Warning ",JOptionPane.WARNING_MESSAGE);
           return ; 
       }
        questions.set(counter, queRef);
       try{
           boolean result=QuestionDAO.updateQuestion(questions);
           if(result==true)
           {
               JOptionPane.showMessageDialog(null,"Paper Succssfully updated","Success",JOptionPane.INFORMATION_MESSAGE);
               new HrQuizOptionFrame().setVisible(true);
               this.dispose();
           }
           else{
               JOptionPane.showMessageDialog(null,"Paper could not be updated","Error !",JOptionPane.ERROR_MESSAGE);
           }
       }
       catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null,"Error in Db","Error !",JOptionPane.ERROR_MESSAGE);
           ex.printStackTrace();
       }
         
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrEditQuizzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrEditQuizzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrEditQuizzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrEditQuizzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrEditQuizzFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiscardPaper;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> jcCorrectOption;
    private javax.swing.JLabel lblHrName;
    private javax.swing.JLabel lblQueNo;
    private javax.swing.JTextField txtOption1;
    private javax.swing.JTextField txtOption2;
    private javax.swing.JTextField txtOption3;
    private javax.swing.JTextField txtOption4;
    private javax.swing.JTextArea txtQuestion;
    // End of variables declaration//GEN-END:variables
}
