/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import javax.swing.JOptionPane;
import trandpl.pojo.CurrentUser;

/**
 *
 * @author hmayw
 */
public class HrOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form HrOptionFrame
     */
    public HrOptionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblHrName.setText(CurrentUser.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHrName = new javax.swing.JLabel();
        btnJobModule = new javax.swing.JButton();
        btnViewAllPrticipants = new javax.swing.JButton();
        btnViewtestResult = new javax.swing.JButton();
        btnVewAllOpenJobs = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Scaled app logo for header
        trandpl.gui.UIUtil.setAppLogo(jLabel1);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 187, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 980, 208));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 302, -1, -1));

        lblHrName.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jPanel1.add(lblHrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 30));

        btnJobModule.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnJobModule.setText("Job Module");
        btnJobModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobModuleActionPerformed(evt);
            }
        });
        jPanel1.add(btnJobModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 392, 289, 36));

        btnViewAllPrticipants.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnViewAllPrticipants.setText("View All Participants");
        btnViewAllPrticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllPrticipantsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAllPrticipants, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 470, 289, 34));

        btnViewtestResult.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnViewtestResult.setText("View Test Result");
        btnViewtestResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewtestResultActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewtestResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 537, 289, 33));

        btnVewAllOpenJobs.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnVewAllOpenJobs.setText("View All Open Jobs");
        jPanel1.add(btnVewAllOpenJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 608, 289, 34));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/worlp-map-in-black-h9i.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 526, 391));

        jButton1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 680, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJobModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobModuleActionPerformed
        new HrJobOptionsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJobModuleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new LoginScreenFrame().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewAllPrticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllPrticipantsActionPerformed
       new HrViewAllParticipants().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnViewAllPrticipantsActionPerformed

    private void btnViewtestResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewtestResultActionPerformed
      int choice = JOptionPane.showConfirmDialog(this,
              "Do you want to see only shortlisted candidates (>= 75%)?\n"
            + "Yes: Show only >= 75%\nNo: Show all completed candidates",
              "View Test Results",
              JOptionPane.YES_NO_CANCEL_OPTION);
      if (choice == JOptionPane.CANCEL_OPTION || choice == JOptionPane.CLOSED_OPTION) {
          return;
      }
      boolean showSelectedOnly = (choice == JOptionPane.YES_OPTION);
      new HrViewTestResult(showSelectedOnly).setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnViewtestResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new HrOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJobModule;
    private javax.swing.JButton btnVewAllOpenJobs;
    private javax.swing.JButton btnViewAllPrticipants;
    private javax.swing.JButton btnViewtestResult;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHrName;
    // End of variables declaration//GEN-END:variables
}
