/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.io.File;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import trandpl.dao.ParticipantsDAO;
import trandpl.pojo.ParticipantPojo;

/**
 *
 * @author hmayw
 */
public class SignUpFrame extends javax.swing.JFrame {

   private File file;
    
    public SignUpFrame() {
        initComponents();
        setLocationRelativeTo(null);
        txtFilePath.setEditable(false);
        loadId();
        
    }
    private  void loadId()
    {
        try{
            int id=ParticipantsDAO.getNewParticipantId();
            lblPrid.setText("Pr-"+id);
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"Error in loading id","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtFilePath = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblPrid = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtSkill3 = new javax.swing.JTextField();
        txtSkill1 = new javax.swing.JTextField();
        txtSkill2 = new javax.swing.JTextField();
        txtSkill4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtQualification = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        pwdCPassword = new javax.swing.JPasswordField();
        jLabel25 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        btnCreateAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Scaled app logo for header
        trandpl.gui.UIUtil.setAppLogo(jLabel1);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 187, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 996, 210));

        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 390, 20));

        txtEmail.setBackground(new java.awt.Color(173, 192, 234));
        txtEmail.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 400, -1));

        txtMobile.setBackground(new java.awt.Color(173, 192, 234));
        txtMobile.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtMobile.setBorder(null);
        jPanel1.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 390, 20));

        txtFilePath.setBackground(new java.awt.Color(173, 192, 234));
        txtFilePath.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtFilePath.setBorder(null);
        jPanel1.add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 300, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel3.setText("Participant Id : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        lblPrid.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jPanel1.add(lblPrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 140, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 330, 10));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 40));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel6.setText("Name :- ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel8.setText("Email :- ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, 20));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel10.setText("Mobile No :- ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 346, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel11.setText("Upload Resume :- ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 344, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Browse File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 960, 10));

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel13.setText("Skills :- ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 424, -1, 30));

        txtSkill3.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtSkill3.setBorder(null);
        jPanel1.add(txtSkill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 462, 180, 30));

        txtSkill1.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtSkill1.setBorder(null);
        jPanel1.add(txtSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 180, 30));

        txtSkill2.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtSkill2.setBorder(null);
        jPanel1.add(txtSkill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 180, 30));

        txtSkill4.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtSkill4.setBorder(null);
        jPanel1.add(txtSkill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 180, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phnNoBtnPic.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, -1, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phnNoBtnPic.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phnNoBtnPic.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phnNoBtnPic.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, 40));

        jLabel18.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel18.setText("Qualification :- ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 30));

        txtQualification.setBackground(new java.awt.Color(173, 192, 234));
        txtQualification.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        txtQualification.setBorder(null);
        jPanel1.add(txtQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 538, 920, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 450, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 960, 10));

        jLabel22.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel22.setText("Password :- ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 584, -1, 30));

        jLabel23.setFont(new java.awt.Font("Cambria", 0, 20)); // NOI18N
        jLabel23.setText("Confirm Password :-");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 584, -1, 30));

        pwdPassword.setBackground(new java.awt.Color(173, 192, 234));
        pwdPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pwdPassword.setBorder(null);
        jPanel1.add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 410, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 460, -1));

        pwdCPassword.setBackground(new java.awt.Color(173, 192, 234));
        pwdCPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pwdCPassword.setBorder(null);
        jPanel1.add(pwdCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 400, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 970, 10));

        jButton2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton2.setText("Login Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 680, -1, 30));

        btnCreateAccount.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 680, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser fileChooser=new JFileChooser();
       fileChooser.setDialogTitle("Select Your Resume");
       fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
       int result=fileChooser.showOpenDialog(null);
       if(result==JFileChooser.APPROVE_OPTION)
       {
           file=fileChooser.getSelectedFile();
           txtFilePath.setText(file.getAbsolutePath());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new LoginScreenFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
      if(!validateInputs())
      {
          JOptionPane.showMessageDialog(null,"Field should not be left blank","Warning",JOptionPane.WARNING_MESSAGE);
          return ;
      }
      if(!pwdMatch())
      {
          JOptionPane.showMessageDialog(null,"Password and confirm password are differennt","Warning",JOptionPane.WARNING_MESSAGE);
          return ; 
      }
      ParticipantPojo pr=new ParticipantPojo();
      
      pr.setId(lblPrid.getText());
      pr.setName(txtName.getText());
      // Store email in lowercase to keep login case-insensitive
      pr.setUserId(txtEmail.getText().trim().toLowerCase());
      pr.setPhone(txtMobile.getText());
      pr.setResume(file);
      pr.setPassword(String.valueOf(pwdPassword.getPassword()));
      pr.setSkills(txtSkill1.getText()+","+txtSkill2.getText()+","+txtSkill3.getText()+","+txtSkill4.getText());
      pr.setQualification(txtQualification.getText());
      // Participant type must match database CHECK constraint ('Participant')
      pr.setType("Participant");
      
      try{
          int result=ParticipantsDAO.addNewParticipant(pr);
          if(result==-1)
          {
              JOptionPane.showInputDialog(null,"UserId is already registered","warning",JOptionPane.WARNING_MESSAGE);
          }
          else if(result==0)
          {
             JOptionPane.showInputDialog(null,"Record could not be added","Error",JOptionPane.ERROR_MESSAGE);
          }
          else{
               JOptionPane.showInputDialog(null,"Record Added","Success",JOptionPane.INFORMATION_MESSAGE);
                clearFields();
                loadId();
          }
      }
      catch(Exception ex)
      {
           JOptionPane.showMessageDialog(null,"Error while Adding Data","DB Error",JOptionPane.INFORMATION_MESSAGE);
           ex.printStackTrace();
           return ; 
      }
    }//GEN-LAST:event_btnCreateAccountActionPerformed
    private void clearFields(){
      txtName.setText("");
      txtEmail.setText("");
      txtMobile.setText("");
      txtFilePath.setText("");
      txtSkill1.setText("");
      txtSkill2.setText("");
      txtSkill3.setText("");
      txtSkill4.setText("");
      txtQualification.setText("");
      pwdPassword.setText("");
      pwdCPassword.setText("");
    }
    
    private boolean validateInputs()
     {
         if(txtName.getText().trim().isEmpty()||txtEmail.getText().trim().isEmpty()||txtMobile.getText().trim().isEmpty()||txtFilePath.getText().trim().isEmpty()||txtSkill1.getText().trim().isEmpty()||txtSkill2.getText().trim().isEmpty()||txtSkill3.getText().trim().isEmpty()||txtSkill4.getText().trim().isEmpty()||txtQualification.getText().trim().isEmpty()||String.valueOf(pwdPassword.getPassword()).isEmpty()||String.valueOf(pwdCPassword.getPassword()).isEmpty())
             return false;
         else
             return true;
     }
     private boolean pwdMatch()
     {
         if(String.valueOf(pwdPassword.getPassword()).equals(String.valueOf(pwdCPassword.getPassword())))
             return true;
         else
             return false;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblPrid;
    private javax.swing.JPasswordField pwdCPassword;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtSkill1;
    private javax.swing.JTextField txtSkill2;
    private javax.swing.JTextField txtSkill3;
    private javax.swing.JTextField txtSkill4;
    // End of variables declaration//GEN-END:variables
}
