/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import trandpl.pojo.ParticipantPojo;
import trandpl.dao.ParticipantsDAO;
import trandpl.dao.UsersDAO;
import trandpl.pojo.CurrentUser;

/**
 *
 * @author hmayw
 */
public class StudentEditProfileFrame extends javax.swing.JFrame {

    private File file;
    private String currentPwd;
    private String newPwd;
    private String cNewPwd;
    
    public StudentEditProfileFrame() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel2.setVisible(false);
        jPanel5.setVisible(false);
        loadData();
    
    }
    private void loadData(){
        try{
              ParticipantPojo pt=ParticipantsDAO.getParticipantDetails(CurrentUser.getId());
              txtName.setText(pt.getName());
              txtPhoneNo.setText(pt.getPhone());
              txtMailAddress.setText(pt.getUserId());
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB Error ","Error !",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtMailAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chChangeResume = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chChangePassword = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        btnSaveChanges = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCNewPwd = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        txtCurrentPwd = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        txtNewPwd = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        btnBrowseFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transparent logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 187, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 980, 208));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Mail Address :- ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Name :- ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Phone No :- ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 316, 300, 30));

        txtPhoneNo.setBackground(new java.awt.Color(173, 192, 234));
        txtPhoneNo.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtPhoneNo.setBorder(null);
        jPanel1.add(txtPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 396, 300, 30));

        txtMailAddress.setBackground(new java.awt.Color(173, 192, 234));
        txtMailAddress.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtMailAddress.setBorder(null);
        jPanel1.add(txtMailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 476, 300, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel9.setText("want to Change Password  ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        chChangeResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chChangeResumeActionPerformed(evt);
            }
        });
        jPanel1.add(chChangeResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 40, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel10.setText("want to change Resume ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 930, 10));

        chChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chChangePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(chChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 40, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 940, 10));

        btnSaveChanges.setText("Save Changes ");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 690, -1, -1));

        jButton2.setText("Discard Changes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 690, -1, -1));

        jPanel2.setBackground(new java.awt.Color(243, 246, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel11.setText("New Password :- ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel12.setText("Confirm New Password :- ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel13.setText("Current Password :- ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(243, 246, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("jLabel11");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel15.setText("jLabel11");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel16.setText("jLabel11");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 470, 160));

        txtCNewPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtCNewPwd.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtCNewPwd.setBorder(null);
        txtCNewPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNewPwdActionPerformed(evt);
            }
        });
        jPanel2.add(txtCNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 290, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 40));

        txtCurrentPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtCurrentPwd.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtCurrentPwd.setBorder(null);
        jPanel2.add(txtCurrentPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 270, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        txtNewPwd.setBackground(new java.awt.Color(173, 192, 234));
        txtNewPwd.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtNewPwd.setBorder(null);
        jPanel2.add(txtNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 75, 290, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TextFieldPic.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 540, 160));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, -1));

        jPanel5.setBackground(new java.awt.Color(243, 246, 254));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("* Upload Resume in within 1000kb ");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -4, -1, 30));

        txtFilePath.setEditable(false);
        txtFilePath.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel5.add(txtFilePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 26, 550, 30));

        btnBrowseFile.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnBrowseFile.setText("Browse File");
        btnBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseFileActionPerformed(evt);
            }
        });
        jPanel5.add(btnBrowseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 27, 150, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 790, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        boolean pwdUpdate=false,resumeUpdate=false;
        if(chChangePassword.isSelected()){
            if(validateInputs()==false){
                JOptionPane.showMessageDialog(null,"Please fill all the fields","Warning ?",JOptionPane.WARNING_MESSAGE);
            }
            else{
               if(matchPwd()){
                    try{
                     boolean resp=UsersDAO.validatePassword(CurrentUser.getId(),this.currentPwd);
                     if(resp==true){
                         try{
                             pwdUpdate=UsersDAO.updateParticipantPassword(CurrentUser.getId(),this.newPwd);
                         }
                         catch(SQLException ex){
                              JOptionPane.showMessageDialog(null,"DB Error","Error !",JOptionPane.ERROR_MESSAGE);
                              ex.printStackTrace();
                         }
                     }
                     else{
                         JOptionPane.showMessageDialog(null,"CurrentPassword dosen't match with oldPassword","Warning",JOptionPane.WARNING_MESSAGE);
                     }
                    }
                   catch(SQLException ex){
                      JOptionPane.showMessageDialog(null,"DB Error","Error !",JOptionPane.ERROR_MESSAGE);
                      ex.printStackTrace();
                  }
               }
               else{
                   JOptionPane.showMessageDialog(null,"Passwords do not match","Password Mismatch",JOptionPane.WARNING_MESSAGE);
               }
            }
        }
        if(chChangeResume.isSelected())
        {
            if(txtFilePath.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Please select a resume ","Warning",JOptionPane.WARNING_MESSAGE);
            }
            else{
                try{
                    resumeUpdate=ParticipantsDAO.updateResume(CurrentUser.getId(), file);
                }
                catch(SQLException ex){
                   JOptionPane.showMessageDialog(null,"DB Error","Error !",JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
                catch(FileNotFoundException ex){
                    JOptionPane.showMessageDialog(null,"DB Error","Error !",JOptionPane.ERROR_MESSAGE);
                      ex.printStackTrace();
                }
            }
        }
        if(pwdUpdate&&resumeUpdate){
            JOptionPane.showMessageDialog(null,"Password and Resume updated successfully ","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(pwdUpdate){
            JOptionPane.showMessageDialog(null,"Password updated successfully ","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(resumeUpdate){
            JOptionPane.showMessageDialog(null,"Resume updated successfully ","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
             JOptionPane.showMessageDialog(null,"No Changes Done","Information",JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_btnSaveChangesActionPerformed
    private boolean validateInputs()
    {
        if(txtCurrentPwd.getPassword().length==0||txtNewPwd.getPassword().length==0||txtCNewPwd.getPassword().length==0)
            return false;
        
        this.currentPwd=String.valueOf(txtCurrentPwd.getPassword());
        this.newPwd=String.valueOf(txtNewPwd.getPassword());
        this.cNewPwd=String.valueOf(txtCNewPwd.getPassword());
        
       return true;
    }
    private boolean matchPwd()
    {
        return newPwd.equals(cNewPwd);
    }
    private void chChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chChangePasswordActionPerformed
      if(chChangePassword.isSelected())
          jPanel2.setVisible(true);
      else
          jPanel2.setVisible(false);
    }//GEN-LAST:event_chChangePasswordActionPerformed

    private void chChangeResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chChangeResumeActionPerformed
        if(chChangeResume.isSelected())
          jPanel5.setVisible(true);
      else
          jPanel5.setVisible(false);
    }//GEN-LAST:event_chChangeResumeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new StudentOptionFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCNewPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNewPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNewPwdActionPerformed

    private void btnBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseFileActionPerformed
          JFileChooser fileChooser=new JFileChooser();
       fileChooser.setDialogTitle("Select Your Resume");
       fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
       int result=fileChooser.showOpenDialog(null);
       if(result==JFileChooser.APPROVE_OPTION)
       {
           file=fileChooser.getSelectedFile();
           txtFilePath.setText(file.getAbsolutePath());
       }
    }//GEN-LAST:event_btnBrowseFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentEditProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentEditProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseFile;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JCheckBox chChangePassword;
    private javax.swing.JCheckBox chChangeResume;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField txtCNewPwd;
    private javax.swing.JPasswordField txtCurrentPwd;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextField txtMailAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtNewPwd;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables
}
