/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import trandpl.pojo.CurrentUser;

/**
 *
 * @author hmayw
 */
public class StudentOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentOptionFrame
     */
    public StudentOptionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblPrName.setText(CurrentUser.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrName = new javax.swing.JLabel();
        btnJobModule = new javax.swing.JButton();
        btnViewAllPrticipants = new javax.swing.JButton();
        btnViewAppliedJobs = new javax.swing.JButton();
        btnVewAllOpenJobs = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Scaled app logo for header
        trandpl.gui.UIUtil.setAppLogo(jLabel1);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 187, 56));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 980, 208));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel3.setText("Welcome ,");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 302, -1, -1));

        lblPrName.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jPanel1.add(lblPrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 210, 30));

        btnJobModule.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnJobModule.setText("Edit Profile");
        btnJobModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobModuleActionPerformed(evt);
            }
        });
        jPanel1.add(btnJobModule, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 392, 289, 36));

        btnViewAllPrticipants.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnViewAllPrticipants.setText("View All Open Jobs");
        btnViewAllPrticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllPrticipantsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAllPrticipants, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 470, 289, 34));

        btnViewAppliedJobs.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnViewAppliedJobs.setText("View All Applied Jobs");
        btnViewAppliedJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAppliedJobsActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAppliedJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 537, 289, 33));

        btnVewAllOpenJobs.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btnVewAllOpenJobs.setText("View All Completed Job");
        btnVewAllOpenJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVewAllOpenJobsActionPerformed(evt);
            }
        });
        jPanel1.add(btnVewAllOpenJobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 608, 289, 34));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newimages/new/ptHomeImg.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 526, 391));

        jButton1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 660, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJobModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobModuleActionPerformed
        new StudentEditProfileFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJobModuleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoginScreenFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewAllPrticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllPrticipantsActionPerformed
      new StudentShowAllOpenJobs().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnViewAllPrticipantsActionPerformed

    private void btnViewAppliedJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAppliedJobsActionPerformed
       new StudentShowAppliedJobs().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnViewAppliedJobsActionPerformed

    private void btnVewAllOpenJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVewAllOpenJobsActionPerformed
       new StudentCompletedJobsFrame().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnVewAllOpenJobsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJobModule;
    private javax.swing.JButton btnVewAllOpenJobs;
    private javax.swing.JButton btnViewAllPrticipants;
    private javax.swing.JButton btnViewAppliedJobs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPrName;
    // End of variables declaration//GEN-END:variables
}
